### ISSUE TITLE
When running a single SimDeep error, I hope to get the author's help

### ISSUE THREAD

**Issue by tqinger** [lanagarmire/DeepProg#10]
In the simple example provided, the last line of code is simDeep.save_encoder('dummy_encoder.h5'), please, what is the .save_encoder method, I run it and get an error

**Comment by lanagarmire** [comment]
This function is to save the encoder for use later. For now, I suggest using the Docker/Singular image as I believe the issue resides with the version changes which causes the serialization to not function correctly. We are working on an update for the latest versions

**Comment by tqinger** [comment]
Thanks for your reply, if you can, can you provide prediction code for simple examples, I would like to use simple examples with using SimDeepBoosting class model predictions as ensemble learning
